version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-apprisal
    ports:
      - "6605:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hr_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./Backend
    container_name: backend-apprisal
    ports:
      - "3045:3045"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: hr_db
      PORT: 3045
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: frontend-apprisal
    ports:
      - "8147:80"
    depends_on:
      - backend
    restart: unless-stopped

  hr:
    build: ./HR
    container_name: hr-apprisal
    ports:
      - "8148:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

